/*
 * File: app/view/MyTabPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mytabpanel',

    requires: [
        'MyApp.view.MyTabPanelViewModel',
        'MyApp.view.MyTabPanelViewController',
        'Ext.Panel'
    ],

    controller: 'mytabpanel',
    viewModel: {
        type: 'mytabpanel'
    },

    items: [
        {
            xtype: 'panel',
            title: 'Normal Tab',
            items: [
                {
                    xtype: 'component',
                    html: 'Click on the other tabs to load the packages'
                }
            ]
        },
        {
            xtype: 'panel',
            pkg: 'Users',
            layout: 'fit',
            iconCls: 'x-fa fa-user',
            title: 'Users'
        },
        {
            xtype: 'panel',
            pkg: 'Groups',
            layout: 'fit',
            iconCls: 'x-fa fa-users',
            title: 'Groups'
        },
        {
            xtype: 'panel',
            pkg: 'Settings',
            layout: 'fit',
            iconCls: 'x-fa fa-cog',
            title: 'Settings'
        }
    ],
    listeners: {
        activeItemchange: 'onTabpanelActiveItemChange'
    }

});