/*
 * File: app/view/MyTabPanelViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyTabPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mytabpanel',

    handlePackage: function(pkg) {
         let tabpanel = this.getView(),
                tab = tabpanel.child('[pkg=' + pkg + ']');

            tabpanel.setMasked(null);

            //only add item if the item isn't already added
            if (!tab.hasPkgItem) {
                tab.hasPkgItem = true;

                tab.add({
                    xclass: 'MyApp.view.' + pkg.toLowerCase() + '.Main'
                });
            }
    },

    onTabpanelActiveItemChange: function(sender, value, oldValue, eOpts) {

        let tabpanel = sender;
        let tab = value;
        let pkg = tab.pkg;

        if (pkg) {
            if (Ext.Package.isLoaded(pkg)) {
                this.handlePackage(pkg);
            } else {
                tabpanel.setMasked({
                    message: 'Loading Package...'
                });

                // let's use little timeout to demostrate the loading
                setTimeout(()=>{
                    Ext.Package
                    .load(pkg)
                    .then(this.handlePackage.bind(this, pkg));
                }, 250);


            }
        }

    }

});